Repository sloalchemist/potions, pull requests merged in 2025-02, with the labels that each got.

#251 180 persist player information
  README.md
  packages/auth-server/src/authController.ts
  packages/auth-server/src/characterData.ts
  packages/auth-server/src/index.ts
  packages/client/src/services/playerToServer.ts
  packages/client/src/services/serverToBroadcast.ts
  packages/common/src/playerToServer.ts
  packages/server/src/mobs/mob.ts
  packages/server/src/mobs/mobFactory.ts
  packages/server/src/services/authMarshalling.ts
  packages/server/src/services/clientCommunication/ablyService.ts
  sql/setup.sql
  supabase/.gitignore
  supabase/config.toml
  supabase/migrations/20250129215219_add_columns_to_characters.sql
  supabase/migrations/20250131062607_load_world.sql
  supabase/migrations/20250131235849_character_view.sql
  terraform/main.tf
Labels: in-game feature, player

#250 Finished Annotating Common Package with JSDocs
  packages/common/src/coord.ts
  packages/common/src/pathFinder.ts
Labels: documentation

#268 Implement favorability assignment
  packages/server/src/community/community.ts
  packages/server/src/favorability/favorability.ts
  packages/server/src/generate/generateWorld.ts
  packages/server/test/mobs/favorability.test.ts
Labels: enhancement, favorability

#271 feat: add player chat
  packages/client/src/config.ts
  packages/client/src/scenes/chatOverlayScene.ts
  packages/client/src/scenes/worldScene.ts
  packages/client/src/services/playerToServer.ts
Labels: enhancement

#291 feat: Establish data pipeline for world_id from client->Supabase
  packages/auth-server/src/characterData.ts
  packages/client/src/scenes/worldScene.ts
  packages/client/src/services/ablySetup.ts
  packages/client/src/services/playerToServer.ts
  packages/client/src/services/serverToBroadcast.ts
  packages/server/src/services/authMarshalling.ts
  packages/server/src/services/clientCommunication/ablyService.ts
Labels: player, important

#315 fix: display speech bubble on speak
  packages/client/src/services/playerToServer.ts
Labels: bug

#273 Fix: client/server item ownership communication
  packages/client/src/sprite/sprite_item.ts
  packages/client/test/items/uses/playerPermissibleInteractions.test.ts
  packages/common/src/item.ts
  packages/server/src/items/uses/create.ts
  packages/server/src/services/clientCommunication/clientMarshalling.ts
Labels: bug

#314 Changed NPC Movement Behavior so They No Longer Walk Over Water
  packages/server/src/mobs/mob.ts
Labels: bug

#353 fix: prevent give item interaction if mob is carrying
  packages/client/src/world/controller.ts
  packages/client/test/items/uses/playerCarriedItems.test.ts
Labels: bug

#357 336 test coverage
  .github/workflows/ci.yml
  .gitignore
  README.md
  package.json
  packages/converse/package.json
  pnpm-lock.yaml
Labels: tests

#397 Refactor #394: Client-side Permissable Interactions
  packages/client/src/sprite/sprite_mob.ts
  packages/client/src/world/controller.ts
  packages/client/test/items/uses/playerPermissibleInteractions.test.ts
  packages/client/test/items/uses/smashGate.test.ts
Labels: refactor

#413 Live reloading for server and client dev scripts
  packages/client/package.json
  packages/client/src/main.ts
  packages/client/webpack.config.js
  packages/server/package.json
  packages/server/src/services/database.ts
  pnpm-lock.yaml
Labels: devops

#425 Bug: Client Error when talking through open gate
  packages/client/src/sprite/sprite_item.ts
  packages/client/src/world/item.ts
  packages/client/src/world/world.ts
  packages/client/src/worldDescription.ts
  packages/client/static/global.json
  packages/client/test/world/pathing.test.ts
Labels: bug

#440 Disable movement and tab-menu clicks when Enter Portal Menu is open
  packages/client/src/scenes/portalMenuScene.ts
Labels: bug

#436 Implement favorite item for Mob
  packages/server/src/items/item.ts
  packages/server/src/items/itemGenerator.ts
  packages/server/src/mobs/mob.ts
  packages/server/src/mobs/mobFactory.ts
  packages/server/test/mobs/favorability.test.ts
Labels: favorability

#434 Remove Player Attribute Fields from Items Tab
  packages/client/src/scenes/uxScene.ts
Labels: bug

#441 Fix Bug #366: Item Ownership Not Persisting for Potion Stand
  packages/server/src/services/clientCommunication/clientMarshalling.ts
Labels: bug

#450 fix: reset movement key state after move
  packages/client/src/scenes/worldScene.ts
Labels: bug

#452 Bug Fix: Update Vscode Task Script
  start_game.sh
Labels: bug

#503 fix: update character animations after color change
  packages/client/src/scenes/uxScene.ts
  packages/client/src/sprite/sprite_mob.ts
Labels: bug

#512 feat: added specialized resource attribute to specialized resources
  packages/client/static/global.json
  packages/json-generator/global.json
Labels: in-game feature

#524 Bug: Game Freezes on Death
  packages/client/src/scenes/loadCharacterScene.ts
  packages/client/src/scenes/loadWorldScene.ts
  packages/client/src/scenes/worldScene.ts
  packages/client/src/services/serverToBroadcast.ts
  packages/client/test/scenes/wordScene.test.ts
Labels: bug

#522 Tick Debugging Logic
  packages/server/src/services/gameWorld/serverWorld.ts
Labels: bug

#527 472 refactor ownedby ownedbycommunity
  packages/client/src/sprite/sprite_item.ts
  packages/client/src/world/controller.ts
  packages/client/src/world/item.ts
  packages/client/test/items/uses/playerBasketInteractions.test.ts
  packages/common/src/item.ts
  packages/server/src/community/house.ts
  packages/server/src/generate/generateWorld.ts
  packages/server/src/items/item.ts
  packages/server/src/items/itemGenerator.ts
  packages/server/src/items/purchasable.ts
  packages/server/src/items/uses/create.ts
  packages/server/src/mobs/mob.ts
  packages/server/src/services/clientCommunication/clientMarshalling.ts
  packages/server/test/actions/create.test.ts
  packages/server/test/items/stand/itemCommunityOwnershipPotionStandInteractions.test.ts
  packages/server/test/potions/favorabilityBasedPotionPurchase.test.ts
  packages/server/test/walls/startWall.test.ts
Labels: refactor

#541 Refining Tab Menus
  packages/client/src/components/button.ts
  packages/client/src/scenes/uxScene.ts
Labels: in-game feature

#534 Bug Fix: Night Overlay Display
  packages/client/src/scenes/worldScene.ts
Labels: bug
