Repository sloalchemist/potions, pull requests merged in 2025-01, with the labels that each got.

#73 Fix: don't display alert when cancel is pressed
  packages/client/src/scenes/loadWorldScene.ts
Labels: bug

#114 fix: don't display health bar for all items
  packages/client/src/sprite/sprite_item.ts
Labels: bug

#152 fix: remove player on character name change
  packages/server/src/mobs/mob.ts
  packages/server/src/services/clientCommunication/ablyService.ts
  packages/server/test/mobs/mob.test.ts
  pnpm-lock.yaml
Labels: bug

#156 Documentation for Server Tests
  packages/server/test/creatingServerTests.md
Labels: documentation

#186 Bug: Multiple Player Interactions Fixed
  packages/client/src/world/controller.ts
  packages/client/test/items/uses/playerInteract.test.ts
Labels: bug

#223 Feature: Create item and mob test templates
  packages/server/test/template/itemTemplate.test.ts
  packages/server/test/template/mobTemplate.test.ts
Labels: enhancement
