Repository sloalchemist/potions, pull requests merged in 2025-03, with the labels that each got.

#595 publish chat messages to clients
  packages/auth-server/src/authController.ts
  packages/client/src/services/ablySetup.ts
  packages/client/src/services/playerToServer.ts
Labels: enhancement

#612 Add Zod Schema Validation to global.json Configuration File
  .gitignore
  packages/client/package.json
  packages/json-generator/jest.config.mjs
  packages/json-generator/package.json
  packages/json-generator/src/generator.ts
  packages/json-generator/src/schema.ts
  packages/json-generator/test/expectedClient.json
  packages/json-generator/test/expectedServer.json
  packages/json-generator/test/index.test.ts
  packages/json-generator/tsconfig.json
  pnpm-lock.yaml
  world_assets/global/client/.gitkeep
  world_assets/global/client/global.json
  world_assets/global/server/.gitkeep
  world_assets/global/server/global.json
Labels: devops

#620 560 implement logging library for server
  packages/server/cli/cheatHandler.ts
  packages/server/package.json
  packages/server/src/favorability/favorability.ts
  packages/server/src/grafana/dataLogger.ts
  packages/server/src/grafana/request.ts
  packages/server/src/items/item.ts
  packages/server/src/items/potionEffects.ts
  packages/server/src/items/uses/enterPortal.ts
  packages/server/src/mobs/mob.ts
  packages/server/src/mobs/plans/hunt.ts
  packages/server/src/services/clientCommunication/ablyService.ts
  packages/server/src/services/gameWorld/serverWorld.ts
  packages/server/src/services/supabaseStorage.ts
  packages/server/src/util/logger.ts
  packages/server/test/actions/enterPortal.test.ts
  packages/server/test/cli/cheatHandler.test.ts
  pnpm-lock.yaml
Labels: devops

#643 feat: Unstash swaps item in inventory with item in hand
  packages/client/src/services/serverToBroadcast.ts
  packages/client/src/sprite/sprite_item.ts
  packages/client/src/world/item.ts
  packages/common/src/serverBroadcast.ts
  packages/converse/test/test.db
  packages/server/src/items/carryable.ts
  packages/server/src/services/clientCommunication/ablyService.ts
  packages/server/src/services/clientCommunication/pubsub.ts
  packages/server/src/services/clientCommunication/stubbedPubSub.ts
  packages/server/test/items/stashAndUnstash.test.ts
  packages/server/test/services/ablyStashUnstash.test.ts
Labels: enhancement, in-game feature

#703 fix: toggleable keybinds manual screen
  packages/client/src/scenes/uxScene.ts
Labels: bug

#717 bug: fixing visual bug that displays obsidian shards
  packages/client/world_assets/fire-world/global-atlas.json
  packages/client/world_assets/fire-world/global.png
Labels: bug, world

#732 Fix: removed redundant stand smash/destroy for potion stands
  packages/client/world_assets/global.json
  packages/json-generator/global.json
  packages/json-generator/test/expectedClient.json
  packages/json-generator/test/expectedServer.json
  packages/server/world_assets/global.json
Labels: bug

#724 fix: add pickup/drop to manual
  packages/client/src/scenes/uxScene.ts
Labels: bug, enhancement, important

#736 Code cleanup. Issue #728
  packages/client/src/components/button.ts
  packages/client/src/components/messageStack.ts
  packages/client/src/components/tabButton.ts
  packages/client/src/scenes/loadWorldScene.ts
  packages/client/src/scenes/uxScene.ts
  packages/client/src/scenes/worldScene.ts
  packages/client/src/sprite/sprite_item.ts
  packages/client/src/world/controller.ts
  packages/client/src/world/item.ts
  packages/client/src/world/mob.ts
  packages/client/src/world/world.ts
  packages/client/src/worldDescription.ts
  packages/common/src/pathFinder.ts
  packages/converse/src/library/knowledge_graph/people/community.ts
  packages/converse/src/library/social/memories/memoryFormation.ts
  packages/converse/src/library/social/speech/starts/askAbout.ts
  packages/json-generator/src/generator.ts
  packages/server/src/grafana/dataLogger.ts
  packages/server/src/grafana/request.ts
  packages/server/src/mobs/mob.ts
  packages/server/src/mobs/mobFactory.ts
  packages/server/src/mobs/plans/chat.ts
  packages/server/src/mobs/plans/flee.ts
  packages/server/src/mobs/plans/gather.ts
  packages/server/src/mobs/plans/heal.ts
  packages/server/src/mobs/plans/means/askForItem.ts
  packages/server/src/mobs/plans/means/goToLastSeen.ts
  packages/server/src/mobs/plans/plan.ts
  packages/server/src/mobs/plans/planMeans.ts
  packages/server/src/mobs/plans/sleep.ts
  packages/server/src/mobs/plans/vandalize.ts
  packages/server/src/services/clientCommunication/ablyService.ts
  packages/server/src/services/database.ts
  packages/server/src/services/gameWorld/serverWorld.ts
  packages/world-generator/src/generateWorld.ts
Labels: bug, urgent, important, refactor

#546 Affiliation check and stat boost
  packages/client/src/world/controller.ts
  packages/client/test/items/uses/playerAffiliationbenefits.test.ts
  packages/server/src/affiliation/affiliation.ts
  packages/server/src/mobs/mob.ts
  packages/server/src/mobs/mobFactory.ts
  packages/server/test/mobs/affiliationBenefits.test.ts
Labels: in-game feature

#765 Fix Phantom Mobs
  packages/client/src/services/serverToBroadcast.ts
Labels: bug

#767 Fix #763: Non-owner community ownership interactions
  packages/client/src/world/controller.ts
  packages/client/test/items/uses/nonOwnerCommunityMemberPermissibleInteractions.test.ts
  packages/client/test/items/uses/playerBasketInteractions.test.ts
  packages/client/test/items/uses/playerCommunityPermissibleInteractions.test.ts
  packages/client/world_assets/global.json
  packages/json-generator/global.json
  packages/server/world_assets/global.json
Labels: bug

#771 Fix #764: Apply individual based ownership to market stand interactions
  packages/client/world_assets/global.json
  packages/json-generator/global.json
  packages/server/world_assets/global.json
Labels: bug

#778 Fix #773: Make potion and market stands walkable
  packages/client/world_assets/global.json
  packages/json-generator/global.json
  packages/server/world_assets/global.json
Labels: bug

#776 fix: Add server logs to gitignore
  .gitignore
Labels: bug

#769 bug: only players who created a stand can destroy it
  packages/client/static/global.json
  packages/client/world_assets/global.json
  packages/json-generator/global.json
  packages/server/src/items/uses/stand/destroyStand.ts
  packages/server/src/items/uses/usesConfig.ts
  packages/server/test/items/stand/itemCharacterOwnershipPotionStandInteractions.test.ts
  packages/server/world_assets/global.json
Labels: bug

#760 Pause menu
  packages/client/src/config.ts
  packages/client/src/scenes/loadWorldScene.ts
  packages/client/src/scenes/pauseMenuScene.ts
  packages/client/src/scenes/worldScene.ts
  packages/server/.gitignore
  packages/server/src/services/gameWorld/.gitignore
  world_assets/global/server/global.json
Labels: in-game feature
